name: Tennis App CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install tennis backend package
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
    
    - name: Run unit tests
      run: |
        pytest tennis_backend/tests/test_tennis_unit.py -v --tb=short
    
    - name: Run utility tests  
      run: |
        pytest tennis_backend/tests/test_unit.py -v --tb=short
    
    - name: Run API tests
      run: |
        pytest tennis_backend/tests/test_endpoints.py -v --tb=short
    
    - name: Run integration tests
      run: |
        pytest tennis_backend/tests/test_tennis_integration.py -v --tb=short
    
    - name: Run all tests with coverage
      run: |
        pip install coverage
        coverage run -m pytest tennis_backend/tests/ -v
        coverage report --show-missing